fun main(){
    print("enter student erollmentnumber:")
    val x= readLine()!!.toBigInteger()
    print("enter student name:")
    val y= readLine()!!.toString()
    print("enter student branch:")
    val br= readLine()!!.toString()
    print("enter student class:")
    val cl= readLine()!!.toString()
    print("enter student batch:")
    val ba= readLine()!!.toString()
    print("enter student college name:")
    val clgn= readLine()!!.toString()
    print("enter student university name:")
    val un= readLine()!!.toString()
    print("enter student age:")
    val sa= readLine()!!.toBigInteger()

    print("***********************************")
    println("Student Info:")
    println()
    println("Enrollment No.=$x")
    println("Name=$y")
    println("Branch=$br")
    println("Class=$cl")
    println("Batch:=$ba")
    println("College Name:$clgn")
    println("University Name:$un")
    println("Age:$sa")
}